# Generated by Django 3.2.8 on 2021-10-27 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 1, 54, 684112, tzinfo=utc)),
        ),
    ]
